<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Auth;

class IntakeOutput extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'chartings_intake_outputs';

    protected $fillable = [
        'patient_id', 'faculty_id', 'logged_at',
        'intake_ml', 'output_ml',
        'intake_oral_ml', 'intake_iv_ml', 'intake_ng_ml',
        'output_urine_ml', 'output_stool_ml', 'output_emesis_ml', 'output_drain_ml',
        // 'balance_ml' is generated by DB if you kept it as a VIRTUAL column
        'remarks',
    ];

    protected $casts = [
        'logged_at'  => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    /** Relationships */
    public function patient() { return $this->belongsTo(Patient::class, 'patient_id'); }
    public function faculty() { return $this->belongsTo(Faculty::class, 'faculty_id'); }

    /** Scopes */
    public function scopeOwned($q, $facultyId = null) {
        $fid = $facultyId ?? Auth::guard('faculty')->id();
        return $fid ? $q->where('faculty_id', $fid) : $q;
    }
    public function scopeForPatient($q, $patientId) { return $q->where('patient_id', $patientId); }
    public function scopeLatestFirst($q) { return $q->orderByDesc('logged_at')->orderByDesc('id'); }

    /** Accessors */
    public function getBalanceAttribute(): ?int
    {
        // If DB VIRTUAL column exists, you can still compute here as fallback
        $in  = (int) ($this->intake_ml ?? 0);
        $out = (int) ($this->output_ml ?? 0);
        return $in - $out;
    }
}
